#!/usr/bin/env python3
"""Sanity-check a pending fund profile draft generated by the auto-promote agent.

Usage:
  python3 scripts/validate_pending_profile.py pending_profiles/<id>.json [--write-validation]

Exit codes:
  0 = all checks pass
  1 = one or more issues (still readable, but flagged)
  2 = file unreadable / malformed
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REQUIRED_FIELDS = ("id", "founded", "aum", "hq", "type_en", "type_zh",
                   "desc_zh", "notable_en", "notable_zh")

HIGH_RISK_MARKERS = ("unknown", "unclear", "tbd", "n/a", "n.a.", "unverified",
                     "估计", "未知", "待定")

DESC_MIN = 50
DESC_MAX = 300
FOUNDED_MIN = 1700
FOUNDED_MAX = 2026


def validate_profile(data: dict) -> dict:
    """Return {ok, issues, high_risk, missing_fields}."""
    issues: list[str] = []
    missing: list[str] = []

    for key in REQUIRED_FIELDS:
        if key not in data or not str(data.get(key, "")).strip():
            missing.append(key)
    if missing:
        issues.append(f"missing required fields: {missing}")

    aum = str(data.get("aum", "")).strip()
    if aum:
        if "$" not in aum and "¥" not in aum and "€" not in aum and "£" not in aum:
            issues.append(f"aum field has no currency symbol: {aum!r}")
        if not re.search(r"\d", aum):
            issues.append(f"aum field has no numeric value: {aum!r}")

    founded = str(data.get("founded", "")).strip()
    if founded:
        m = re.fullmatch(r"\d{4}", founded)
        if not m:
            issues.append(f"founded field not 4-digit year: {founded!r}")
        elif not (FOUNDED_MIN <= int(founded) <= FOUNDED_MAX):
            issues.append(
                f"founded year {founded} out of range "
                f"{FOUNDED_MIN}-{FOUNDED_MAX}"
            )

    hq = str(data.get("hq", "")).strip()
    if hq and "," not in hq:
        issues.append(
            f"hq field missing comma (expected 'City, Country' format): {hq!r}"
        )

    desc_zh = str(data.get("desc_zh", "")).strip()
    if desc_zh:
        n = len(desc_zh)
        if n < DESC_MIN:
            issues.append(f"desc_zh too short ({n} chars, need ≥{DESC_MIN})")
        elif n > DESC_MAX:
            issues.append(f"desc_zh too long ({n} chars, max {DESC_MAX})")

    high_risk = False
    risk_hits: list[str] = []
    for k, v in data.items():
        if not isinstance(v, str) or k.startswith("_"):
            continue
        for marker in HIGH_RISK_MARKERS:
            if marker.lower() in v.lower():
                risk_hits.append(f"{k}: '{marker}' → {v[:60]}")
                high_risk = True
                break
    if risk_hits:
        issues.append(f"high-risk uncertainty markers: {risk_hits}")

    return {
        "ok": len(issues) == 0,
        "issues": issues,
        "high_risk": high_risk,
        "missing_fields": missing,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", help="path to pending_profiles/<id>.json")
    parser.add_argument(
        "--write-validation",
        action="store_true",
        help="write companion <id>.validation.json with the result",
    )
    args = parser.parse_args()

    profile_path = Path(args.path)
    if not profile_path.exists():
        print(f"ERROR: file not found: {profile_path}", file=sys.stderr)
        return 2

    try:
        data = json.loads(profile_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"ERROR: malformed JSON: {exc}", file=sys.stderr)
        return 2

    result = validate_profile(data)
    result["validated_at"] = datetime.now(timezone.utc).isoformat()
    result["profile_path"] = str(profile_path)

    if args.write_validation:
        validation_path = profile_path.with_suffix(".validation.json")
        validation_path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
        print(f"Validation written: {validation_path}")

    if result["ok"]:
        print(f"OK: {profile_path.name} passes all sanity checks")
    else:
        print(f"ISSUES ({len(result['issues'])}):")
        for issue in result["issues"]:
            print(f"  - {issue}")
        if result["high_risk"]:
            print("  ⚠️ HIGH-RISK: uncertainty markers present, manual review urgent")

    return 0 if result["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
