#!/usr/bin/env python3
"""Sanity-check a pending fund profile draft generated by the auto-promote agent.

Usage:
  python3 scripts/validate_pending_profile.py pending_profiles/<id>.json [--write-validation]

Exit codes:
  0 = all checks pass
  1 = one or more issues (still readable, but flagged)
  2 = file unreadable / malformed
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REQUIRED_FIELDS = ("id", "founded", "aum", "hq", "type_en", "type_zh",
                   "desc_zh", "notable_en", "notable_zh")

# Evidence fields: a citation (URL or domain) the agent must record after
# web-verifying the corresponding fact. The whole point of the auto-graduate
# gate is that AUM/founded are *checked against a source*, not recalled from
# the model's parametric memory (which is where the PineBridge ~$190B and the
# Ares ~$450B confabulations came from). No source → not auto-graduatable.
EVIDENCE_FIELDS = {"aum": "aum_source", "founded": "founded_source"}

HIGH_RISK_MARKERS = ("unknown", "unclear", "tbd", "n/a", "n.a.", "unverified",
                     "reportedly", "rumored", "circa", "estimated",
                     "估计", "未知", "待定", "推测", "据传", "存疑")

DESC_MIN = 50
DESC_MAX = 300
FOUNDED_MIN = 1700
FOUNDED_MAX = 2026

# AUM plausibility band (rough USD magnitude). Catches absurd values
# (e.g. "$50T", "$5") but NOT in-band confabulations — the evidence
# requirement is what guards the latter.
AUM_MIN_USD = 1e7   # $10M
AUM_MAX_USD = 2e13  # $20T

# A citation must look like a real source: a URL or a bare domain.
_CITATION_RE = re.compile(
    r"https?://\S+|\b[\w-]+\.(?:com|org|gov|net|edu|io|co|cn|uk|asia)\b", re.I)

# Currency-prefixed money token, e.g. "$190B", "€2.2T", "~$500M".
_MONEY_TOKEN_RE = re.compile(r"[\$¥€£]\s*(\d+(?:\.\d+)?)\s*([KMBT])\b", re.I)

_UNIT_MULT = {"k": 1e3, "m": 1e6, "b": 1e9, "t": 1e12}


def _money_tokens(text: str) -> set[str]:
    """Normalised currency-figure tokens in `text`, e.g. {'190b', '2.2t'}.
    Currency symbol is ignored on purpose (we compare magnitudes, not FX)."""
    return {f"{num}{unit.lower()}"
            for num, unit in _MONEY_TOKEN_RE.findall(text or "")}


def _aum_usd_magnitude(aum: str) -> float | None:
    """Rough USD magnitude of the first money token in `aum`, or None if the
    value has no parseable number+unit (e.g. '$15T+ benchmarked' still parses
    the 15T part; 'lots of money' returns None)."""
    m = _MONEY_TOKEN_RE.search(aum or "")
    if not m:
        return None
    try:
        return float(m.group(1)) * _UNIT_MULT[m.group(2).lower()]
    except (ValueError, KeyError):
        return None


def validate_profile(data: dict) -> dict:
    """Return {ok, issues, high_risk, missing_fields}."""
    issues: list[str] = []
    missing: list[str] = []

    for key in REQUIRED_FIELDS:
        if key not in data or not str(data.get(key, "")).strip():
            missing.append(key)
    if missing:
        issues.append(f"missing required fields: {missing}")

    aum = str(data.get("aum", "")).strip()
    if aum:
        if "$" not in aum and "¥" not in aum and "€" not in aum and "£" not in aum:
            issues.append(f"aum field has no currency symbol: {aum!r}")
        if not re.search(r"\d", aum):
            issues.append(f"aum field has no numeric value: {aum!r}")
        mag = _aum_usd_magnitude(aum)
        if mag is not None and not (AUM_MIN_USD <= mag <= AUM_MAX_USD):
            issues.append(
                f"aum magnitude implausible: {aum!r} parses to ~${mag:,.0f} "
                f"(expected ${AUM_MIN_USD:,.0f}–${AUM_MAX_USD:,.0f})"
            )

    founded = str(data.get("founded", "")).strip()
    if founded:
        m = re.fullmatch(r"\d{4}", founded)
        if not m:
            issues.append(f"founded field not 4-digit year: {founded!r}")
        elif not (FOUNDED_MIN <= int(founded) <= FOUNDED_MAX):
            issues.append(
                f"founded year {founded} out of range "
                f"{FOUNDED_MIN}-{FOUNDED_MAX}"
            )

    # Evidence requirement: each verifiable fact (aum, founded) must carry a
    # citation that looks like a real source (URL or domain). Missing/weak
    # evidence is a HARD issue → blocks auto-graduate (and prompts the human to
    # record the source they verified against before a manual graduate).
    for fact, src_field in EVIDENCE_FIELDS.items():
        if not str(data.get(fact, "")).strip():
            continue  # absence already reported by missing-fields check
        src = str(data.get(src_field, "")).strip()
        if not src:
            issues.append(
                f"missing evidence: {src_field} required to back {fact!r} "
                f"(record a source URL — verify, don't recall from memory)"
            )
        elif not _CITATION_RE.search(src):
            issues.append(
                f"{src_field} is not a citation (need a URL or domain): {src!r}"
            )

    hq = str(data.get("hq", "")).strip()
    if hq and "," not in hq:
        issues.append(
            f"hq field missing comma (expected 'City, Country' format): {hq!r}"
        )

    desc_zh = str(data.get("desc_zh", "")).strip()
    if desc_zh:
        n = len(desc_zh)
        if n < DESC_MIN:
            issues.append(f"desc_zh too short ({n} chars, need ≥{DESC_MIN})")
        elif n > DESC_MAX:
            issues.append(f"desc_zh too long ({n} chars, max {DESC_MAX})")

    # AUM internal-consistency: when both the structured aum field and desc_zh
    # state a currency figure, they must share at least one. Catches the LLM
    # self-contradiction case (aum="$100B" but desc says "$190B"). Conservative:
    # only fires when both sides carry a parseable currency token, so a desc
    # written in Chinese 亿/万亿 notation (no $ token) never false-positives.
    aum_tokens = _money_tokens(aum)
    desc_tokens = _money_tokens(desc_zh)
    if aum_tokens and desc_tokens and aum_tokens.isdisjoint(desc_tokens):
        issues.append(
            f"aum/desc_zh figure mismatch: aum has {sorted(aum_tokens)} but "
            f"desc_zh has {sorted(desc_tokens)} (possible confabulation)"
        )

    high_risk = False
    risk_hits: list[str] = []
    for k, v in data.items():
        if not isinstance(v, str) or k.startswith("_"):
            continue
        for marker in HIGH_RISK_MARKERS:
            if marker.lower() in v.lower():
                risk_hits.append(f"{k}: '{marker}' → {v[:60]}")
                high_risk = True
                break
    if risk_hits:
        issues.append(f"high-risk uncertainty markers: {risk_hits}")

    return {
        "ok": len(issues) == 0,
        "issues": issues,
        "high_risk": high_risk,
        "missing_fields": missing,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", help="path to pending_profiles/<id>.json")
    parser.add_argument(
        "--write-validation",
        action="store_true",
        help="write companion <id>.validation.json with the result",
    )
    args = parser.parse_args()

    profile_path = Path(args.path)
    if not profile_path.exists():
        print(f"ERROR: file not found: {profile_path}", file=sys.stderr)
        return 2

    try:
        data = json.loads(profile_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"ERROR: malformed JSON: {exc}", file=sys.stderr)
        return 2

    result = validate_profile(data)
    result["validated_at"] = datetime.now(timezone.utc).isoformat()
    result["profile_path"] = str(profile_path)

    if args.write_validation:
        validation_path = profile_path.with_suffix(".validation.json")
        validation_path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n")
        print(f"Validation written: {validation_path}")

    if result["ok"]:
        print(f"OK: {profile_path.name} passes all sanity checks")
    else:
        print(f"ISSUES ({len(result['issues'])}):")
        for issue in result["issues"]:
            print(f"  - {issue}")
        if result["high_risk"]:
            print("  ⚠️ HIGH-RISK: uncertainty markers present, manual review urgent")

    return 0 if result["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
